data:
  train_file: 'filelist/train.txt'
  val_file: 'filelist/valid.txt'
#############################
train:
  num_workers: 4
  batch_size: 6
  optimizer: 'adam'
  seed: 1234
  adam:
    lr: 0.0002
    beta1: 0.8
    beta2: 0.99
  mel_lamb: 5
  stft_lamb: 2.5
#############################
audio:
  n_mel_channels: 80
  segment_length: 12000 # Should be multiple of 160
  filter_length: 2048
  hop_length: 480 # WARNING: this can't be changed.
  win_length: 2048
  sampling_rate: 48000
  mel_fmin: 0.0
  mel_fmax: 24000.0
#############################
gen:
  input_channels: 100
  upsample_rates: [6,5,4,2,2]
  upsample_kernel_sizes: [20,15,12,4,4]
  upsample_initial_channel: 512
  resblock_kernel_sizes: [3,7,11]
  resblock_dilation_sizes: [[1,3,5], [1,3,5], [1,3,5]]
#############################
mpd:
  periods: [2,3,5,7,11]
  kernel_size: 5
  stride: 3
  use_spectral_norm: False
  lReLU_slope: 0.2
#############################
mrd:
  resolutions: "[(1024, 120, 600), (2048, 240, 1200), (512, 50, 240)]" # (filter_length, hop_length, win_length)
  use_spectral_norm: False
  lReLU_slope: 0.2
#############################
dist_config:
  dist_backend: "nccl"
  dist_url: "tcp://localhost:54321"
  world_size: 1
#############################
log:
  info_interval: 100
  eval_interval: 1000
  save_interval: 10000
  num_audio: 6
  pth_dir: 'chkpt'
  log_dir: 'logs'
